#!/bin/bash
#
# SPDX-License-Identifier: Apache-2.0
##############################################################################
# Copyright (c) 2018 IBM Corporation, The Linux Foundation and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License 2.0
# which accompanies this distribution, and is available at
# https://www.apache.org/licenses/LICENSE-2.0
##############################################################################

ARTIFACT_DIR=".sign-artifacts"
SIGNATURES_DIR="gpg-signatures"


function print_usage {
    echo "Usage: $0 sign <url>"
    echo ""
    echo "    sign   : Downloads and Signs artifacts from Nexus"
}


# Downloads artifacts from a Nexus URL and creates gpg signatures for them
# and copies the signatures to a separate directory.
function sign {
    echo "Signing artifacts..."

    if [ -d "$ARTIFACT_DIR" ]; then
        echo "$ARTIFACT_DIR directory exists. Clearing..."
        rm -rf $ARTIFACT_DIR
    fi

    mkdir $ARTIFACT_DIR
    cd $ARTIFACT_DIR

    echo "Fetching artifact $URL"
    # Fetch Artifacts
    wget $URL

    ARTIFACT=`ls`

    echo "Signing $ARTIFACT"
    gpg2 --batch -abq $ARTIFACT

    cd ..

    if [ -d "$SIGNATURES_DIR" ]; then
        echo "$SIGNATURES_DIR directory exists. Clearing..."
        rm -rf $SIGNATURES_DIR
    fi

    rsync -avz --include '*/' --include '*.asc' --exclude '*' \
           "${ARTIFACT_DIR}" "${SIGNATURES_DIR}"
}


if [ -z "$2" ]; then
    print_usage
    exit 1
fi

MODE=$1
URL=$2

if [ "$MODE" == "sign" ]; then
    sign
else
    echo "ERROR: Invalid mode."
    print_usage
    exit 1
fi
